[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-lint"
name = "ruff (lint)"
language = "system"
entry = "ruff check --fix"
types = ["python"]

[[repos.hooks]]
id = "ruff-format"
name = "ruff (format)"
language = "system"
entry = "ruff format"
types = ["python"]

[[repos.hooks]]
id = "mypy"
name = "mypy"
language = "system"
entry = "mypy ors_launcher"
pass_filenames = false
types = ["python"]
