"""Pydantic schema for the subset of ors-config.yml this tool manages.

Every model allows extra fields so hand-edited advanced upstream keys
(ext_storages, encoder_options, ors.endpoints, ors.cors, ...) round-trip
through load/dump unchanged instead of being rejected.

`launcher` is the one section here that is NOT part of ORS's own config
schema -- it holds JVM heap sizes that `start` needs but ORS itself ignores.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from .constants import DEFAULT_PROFILES, LOG_FILE_NAME


class ElevationConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    preprocessed: bool = False
    data_access: Literal["MMAP", "RAM_STORE"] = "MMAP"
    cache_path: str = "elevation_cache"
    cache_clear: bool = False
    provider: Literal["multi", "cgiar", "srtm"] = "multi"


class ProfileBuildConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    source_file: str
    elevation: bool = True


class ProfileConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool = True
    build: ProfileBuildConfig | None = None


class ProfileDefaultConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    build: ProfileBuildConfig


class EngineConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    elevation: ElevationConfig = Field(default_factory=ElevationConfig)
    profile_default: ProfileDefaultConfig
    profiles: dict[str, ProfileConfig]


class EndpointConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool = True


class IsochronesEndpointConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool = True
    maximum_intervals: int = 10


class MatrixEndpointConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool = True
    maximum_visited_nodes: int = 10_000_000


class SnapEndpointConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool = True
    attribution: str = "openrouteservice.org, OpenStreetMap contributors"
    maximum_locations: int = 5000


class EndpointsConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    routing: EndpointConfig = Field(default_factory=EndpointConfig)
    isochrones: IsochronesEndpointConfig = Field(
        default_factory=IsochronesEndpointConfig
    )
    matrix: MatrixEndpointConfig = Field(default_factory=MatrixEndpointConfig)
    snap: SnapEndpointConfig = Field(default_factory=SnapEndpointConfig)


class OrsSection(BaseModel):
    model_config = ConfigDict(extra="allow")

    engine: EngineConfig
    endpoints: EndpointsConfig = Field(default_factory=EndpointsConfig)


class ServerConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    port: int = 8080


class LoggingFileConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str = "logs/ors.log"


class LoggingLevelConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    root: str = "WARN"


class LoggingConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    file: LoggingFileConfig = Field(default_factory=LoggingFileConfig)
    level: LoggingLevelConfig = Field(default_factory=LoggingLevelConfig)


class LauncherConfig(BaseModel):
    """JVM heap sizing used by `start`. Not part of the upstream ORS schema."""

    java_xms: str = "2g"
    java_xmx: str = "12g"


class OrsLauncherConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    server: ServerConfig = Field(default_factory=ServerConfig)
    ors: OrsSection
    logging: LoggingConfig = Field(default_factory=LoggingConfig)
    launcher: LauncherConfig = Field(default_factory=LauncherConfig)


def load_config(path: Path) -> OrsLauncherConfig:
    raw = yaml.safe_load(path.read_text()) or {}
    return OrsLauncherConfig.model_validate(raw)


def dump_config(config: OrsLauncherConfig, path: Path) -> None:
    data = config.model_dump(mode="json", exclude_none=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False))


def render_validation_error(exc: ValidationError) -> str:
    """Format a ValidationError as one field-path/reason line per error."""
    lines = []
    for err in exc.errors():
        loc = ".".join(str(part) for part in err["loc"]) or "<root>"
        lines.append(f"{loc}: {err['msg']}")
    return "\n".join(lines)


def build_default_config(
    *,
    osm_file: Path,
    port: int,
    log_dir: Path,
    elevation_cache_dir: Path,
) -> OrsLauncherConfig:
    """Build the default config generated by `init`/`start` for a fresh install."""
    return OrsLauncherConfig(
        server=ServerConfig(port=port),
        ors=OrsSection(
            engine=EngineConfig(
                elevation=ElevationConfig(cache_path=str(elevation_cache_dir)),
                profile_default=ProfileDefaultConfig(
                    build=ProfileBuildConfig(source_file=str(osm_file), elevation=True)
                ),
                profiles={
                    name: ProfileConfig(enabled=True) for name in DEFAULT_PROFILES
                },
            ),
            endpoints=EndpointsConfig(),
        ),
        logging=LoggingConfig(
            file=LoggingFileConfig(name=str(log_dir / LOG_FILE_NAME))
        ),
    )
